/**
 * Intelligence subsystem contracts.
 * These types are always compiled but the intelligence domain
 * is disabled by default. When enabled, it subscribes to dispatch
 * events and can override declarative rules with learned routing.
 */

export interface Intent {
  task: string;
  category: "coding" | "review" | "research" | "testing" | "refactoring" | "planning" | "documentation" | "unknown";
  complexity: "simple" | "moderate" | "complex";
  estimatedTokens: number;
  /** Confidence in the classification (0 to 1). */
  confidence: number;
  /** Extracted file paths mentioned in the task (for speculative pre-read). */
  mentionedPaths: string[];
  /** Suggested model tier based on task complexity. */
  suggestedTier: "frontier" | "mid" | "small" | "any";
}

export interface DispatchPlan {
  intent: Intent;
  agent: string;
  model: string | null;
  parallel: boolean;
  estimatedCost: number;
  confidence: number;
  /** When true, the plan was generated by learned rules rather than static mapping. */
  learned: boolean;
}

export interface DispatchOutcome {
  runId: string;
  plan: DispatchPlan;
  success: boolean;
  actualCost: number;
  actualTokens: number;
  durationMs: number;
  /** Exit code from the worker. */
  exitCode: number;
  /** Agent that was used (may differ from plan if fallback occurred). */
  actualAgent: string;
  /** Model that was used (may differ from plan if routing changed). */
  actualModel: string | null;
}

/**
 * Outcome statistics for a (category, agent) pair.
 * Used by the learner to inform future routing decisions.
 */
export interface OutcomeStats {
  category: Intent["category"];
  agent: string;
  totalDispatches: number;
  successCount: number;
  averageCost: number;
  averageDurationMs: number;
  successRate: number;
}
